---

- name: Create infra in AWS
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - deploy_infra

  post_tasks:

    - name: Refresh ansible inventory
      meta: refresh_inventory


- name: Configure EC2 instance
  hosts: "{{ hostvars['localhost']['ec2_public_ip'] }}"  # Extract ec2 ip from localhost vars
  gather_facts: False
  become: True

  pre_tasks:
    - name: Retrieve RDS endpoint from localhost hostvars
      set_fact:
        rds_endpoint: "{{ hostvars['localhost']['rds']['DBInstances'][0]['Endpoint']['Address'] }}"

  roles:
    - install_app


- name: Clean up
  hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - post_deploy