---

- name: Create a VPC
  ec2_vpc_net:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    name: TechChallengeApp_VPC
    region: "{{ aws_region }}"
    cidr_block: "{{ cidr_block }}"
    tags:
      purpose: techchallenge
    state: present
  register: aws_vpc

- name: Create VPC subnets in two availability zones
  ec2_vpc_subnet:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    region: "{{ aws_region }}"
    az: "{{ item.az }}"
    vpc_id: "{{ aws_vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    tags: 
      purpose: techchallenge
    state: present
  loop: "{{ aws_availability_zones }}"
  register: aws_vpc_subnets

- name: Extract VPN subnet ID  # Just one will do
  set_fact:
    vpc_subnet_id: "{{ item.subnet.id }}"
  loop: "{{ aws_vpc_subnets.results }}"

# - name: Create security group