---

- name: Create an EC2 instance
  ec2:
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    instance_type: t2.micro
    image: ami-0bf594d29332cb4e8  # EC2 Linux AMI for ap-southeast-2
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    wait: yes
    instance_tags:
      Name: "servian_todoapp"
      Creator: Ansible
      OS: Linux
    state: present

# - wait_for: path={{ hostpath }} search_regex={{hoststring}}

# - name: Wait for SSH to come up before proceeding
#   local_action: wait_for 
#                 host={{ item.public_ip }} 
#                 port=22 
#                 state=started
#   with_items: ec2.instances