---

# Runs on EC2 instance (created by deploy_infra role)

- name: App installation
  block:

  - name: Prepare the EC2 instance
    include_tasks: 1-prepare_server.yml

  - name: Create the app service
    include_tasks: 2-create_service.yml