---

# Create an ec2 key to use with the ec2 instance
# This key is required to install the app on the server
# After the app has been deployed, SSH will be closed to the outside world

- name: Create an EC2 key
  amazon.aws.ec2_key:
    name: "{{ app_name }}-key"
    region: "{{ aws_region }}"
    force: True
  register: ec2_key
  ignore_errors: True

- name: Save private key
  copy:
    content: "{{ ec2_key.key.private_key }}"
    dest: "/work/ec2_key"
    mode: 0600
  become: True
  ignore_errors: True