---

- name: Create an EC2 instance
  amazon.aws.ec2:
    instance_type: t2.micro
    image: ami-0f96495a064477ffb  # EC2 Linux AMI for ap-southeast-2
    key_name: "{{ app_name }}-key"
    region: "{{ aws_region }}"
    vpc_subnet_id: "{{ vpc_subnets | map(attribute='subnet.id') | first }}"
    instance_tags:
      Name: "{{ app_name }}"
      Creator: Ansible
      OS: Linux
    group:
      - default
      - webservers
    assign_public_ip: True
    wait: True
    state: present
  register: ec2

- name: print ec2 result
  debug: msg={{ item }}
  loop: "{{ ec2.instances }}"

- name: Create /etc/ansible directory
  file:
    path: /etc/ansible
    state: directory
    mode: 0755

- name: Create ansible hosts file
  file:
    path: /etc/ansible/hosts
    state: touch
    mode: 0755

- name: Add host to ansible hosts
  copy:
    dest: /etc/ansible/hosts
    content: |
      [local]
      localhost
      [appservers]
      {{ item.public_ip }} ansible_ssh_user=ec2-user ansible_ssh_private_key_file={{ ec2_key_path }} ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
  loop: "{{ ec2.instances }}"

# Reload ansible inventory so that we can target the newly
# added instance in the next play
- name: Reload hosts file
  meta: refresh_inventory