---

# This task list waits for the EC2 and RDS instances to come up before proceeding

- name: Wait for SSH to EC2 instance to come up
  wait_for: 
    host: "{{ item.public_ip }}"
    port: 22 
    state: started
  loop: "{{ ec2.instances }}"

- name: Extract EC2 instance public IP
  set_fact:
    ec2_public_ip: "{{ ec2.instances[0].public_ip }}"

- name: Wait for RDS instance to come up (this could take a while)
  async_status:
    jid: "{{ rds_job.ansible_job_id }}"
  register: rds_deployment
  until: rds_deployment.finished
  retries: 200

- name: Get RDS instance details
  community.aws.rds_instance_info:
    db_instance_identifier: "{{ app_name }}-db"
    region: "{{ aws_region }}"
  register: rds