---

# - name: Validate variables provided (in group_vars\all)
# amazon.aws.aws_az_info

- name: Deployment block
  block:

  - name: Set up AWS environment
    include_tasks: 1-setup_environment.yml

  - name: Create SSH key
    include_tasks: 2-create_key.yml

  # - name: Create RDS instance
  #   include_tasks: 3-create_rds_instance.yml

  - name: Create EC2 instance
    include_tasks: 4-create_ec2_instance.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ secret_key }}"